# Based on https://qxf2.com/blog/tox-with-circleci/
version: 2
jobs:
  build:
      docker:
        - image: circleci/python:3.7
      steps:
        - checkout
        - run: python -m venv venv
        - run: venv/bin/pip install -r requirements_dev.txt
        - run: echo "source /root/project/venv/bin/activate" >> $BASH_ENV
        - run: python setup.py bdist_wheel
  test:
      docker:
        - image: themattrix/tox
      steps:
        - checkout
        - run: apt-get -y update
        - run: apt-get -y install ipython
        - run: python -m venv venv
        - run: venv/bin/pip install jupyter
        - run: venv/bin/pip install -r requirements_dev.txt
        - run: echo "source /root/project/venv/bin/activate" >> $BASH_ENV
        - run: python setup.py develop
        # - run: pytest -s --junitxml=test_results/pytest/pytest-report.xml
        - run: tox -q
        - store_test_results:
            path: test_results
        - store_artifacts:
            path: test_results
workflows:
  version: 2
  tests:
    jobs:
      - test
  build:
    jobs:
      - build
