# Based on https://qxf2.com/blog/tox-with-circleci/
version: 2
jobs:
  # While this job isn't in a workflow, it works. Kept around for reference.
  deploy:
      docker:
        - image: circleci/python:3.7
      steps:
        - checkout
        - run: python -m venv venv
        - run: venv/bin/pip install -r requirements_dev.txt
        - run: echo "source /home/circleci/project/venv/bin/activate" >> $BASH_ENV
        - run: python setup.py sdist bdist_wheel
        - run:
            name: init .pypirc
            command: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
        - run:
            name: upload to pypi
            command: venv/bin/twine upload dist/*
        - store_artifacts:
            path: dist
  test:
      parameters:
        env:
          type: string
      docker:
        - image: themattrix/tox
      steps:
        - checkout
        - run: apt-get -y update
        - run: apt-get -y install ipython
        - run: apt-get -y install nano
        - run: apt-get -y install git
        - restore_cache:  # ensure this step occurs *before* installing dependencies
            key: deps-0-{{ .Branch }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "setup.py" }}
        - run: python -m venv venv
        - run: venv/bin/pip install jupyter
        - run: venv/bin/pip install -r requirements_dev.txt
        - run: echo "source /root/project/venv/bin/activate" >> $BASH_ENV
        - run: tox -e << parameters.env >>
        - save_cache:
            # Had trouble w/the full cache key reaching into the template dir
            # key: deps-0-{{ .Branch }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "setup.py" }}-{{ checksum "whisk/template/\{\{\ cookiecutter.repo_name\ \}\}/requirements.txt"}}
            key: deps-0-{{ .Branch }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "setup.py" }}
            paths:
              - "venv"
              - ".tox"
              # installed with created project via `whisk setup`
              - "/tmp/pytest-of-root/"
        - store_test_results:
            path: test_results
        - store_artifacts:
            path: test_results
workflows:
  version: 2
  test_py37:
    jobs:
      - test:
          context: whisk
          env: py37
  test_py38:
    jobs:
      - test:
          context: whisk
          env: py37
